---
title: "WoLKE-Studie-2026"
author: "Benedikt Beuttler"
date: "`r Sys.Date()`"
lang: en
page-layout: full
document-css: false
link-citations: true
number-sections: true
toc: true
csl: https://www.zotero.org/styles/apa
bibliography: library.bib
editor: source
execute:
  cache: true
format:
  html:
    standalone: true
    embed-resources: true
    section-divs: true
    html-math-method: mathjax
    wrap: none
    default-image-extension: png
    date-format: long  
    code-fold: true
    code-tools: true
  docx: 
    toc: true
    toc-depth: 2
    number-sections: true
    fig-caption: true
    fig-format: pdf
    default-image-extension: pdf
    date-format: long
    keep-md: true
    echo: false
    code-fold: true
prefer-html: true
---


```{r Information for first time user to get started with renv}
#| output: false
if (FALSE) {
  install.packages("renv") #1
  renv::restore() #2
}
```


```{r load-libraries-and-functions}
#| output: false

# install pacman
if (!requireNamespace("pacman", quietly = TRUE)) {
  install.packages("pacman")
}
library(pacman)

## Pfad/Utilities
p_load(this.path)

## Wrangling
# use pacman to load packages
p_load(dplyr, tidyr, stringr, forcats, purrr, magrittr)

## Ähnlichkeit/Text
p_load(stringdist, psych)

## Modellierung
p_load(lavaan, lme4, lmerTest, emmeans, estimatr)

## Tabellen/Reporting
p_load(modelsummary, kableExtra, arsenal)

## Visualisierung/Themes
p_load(ggplot2, ggsci, jtools)

p_load(mnormt)

source(file = "functions.r") # all outsourced funtions
```


## Load Pre- and Posttest and Reshape Data

```{r load and prepare data}

# load pre-prepared data
load("data/data_all.Rdata")
load("data/data.Rdata")

```

```{r Demographics}
# Generate the tableby summary
preprocess_data <- function(data_all) {
  data %>%
    droplevels() %>%
    mutate(
      studies = fct_infreq(studies),
      subject1 = fct_infreq(subject1),
      subject2 = fct_infreq(subject2)
    )
}

# only get data from pretest for demographic data to see registered
# data_pretest <- data_all %>%
#   filter(time == "pre")

# nrow(data_pretest) # amount of registered participants 145

# only take samples with pre and post test data into account, singlecodes
data_dem_all <- data_all %>%
  group_by(code) %>%
  filter(all(c("pre", "post") %in% time)) %>%
  filter(time == "post") %>%
  ungroup()
nrow(data_dem_all) # 78 participants with pre and post test

# Create the formula
demographics_formula <- intervention ~
  location + age + gender + semester + isp + studies #+ subject1 + subject2
demographics <- tableby(demographics_formula, data = data_dem_all)

# Ausgabe als Tabellen
summary(demographics) %>%
  as.data.frame() %>%
  knitr::kable(caption = "Demographic Summary")

# Welche Fächer gibt es wie oft?
subject_counts <- data_dem_all %>%
  group_by(intervention) %>%
  pivot_longer(
    c(subject1, subject2),
    names_to = "slot",
    values_to = "subject"
  ) %>%
  mutate(subject = str_squish(subject)) %>%
  filter(!is.na(subject), subject != "") %>%
  count(subject, sort = TRUE, name = "n") #%>%
# mutate(p = n / sum(n))

print(n = 100, subject_counts)

```

```{r Prepare scales}

### grouping scales
## TPACK
# all TPACK items used
list_items_i_tpack <- list(
  "TK" = grep("^TP01_", names(data), value = T),
  "TPK" = grep("^TP02_", names(data), value = T),
  "TCK" = grep("^TP03_", names(data), value = T),
  "TPACK_ce" = grep("^TP04_(0[1-8]|12|15)$", names(data), value = T), # Sub-Subskala 1: Celik Enhanced Items
  "TPACK_genai" = grep("^TP04_(09|10|11|13|14)$", names(data), value = T), # Sub-Subskala 2: GenAI Items
  "Ethics" = grep("^TP05_0[1-6]$", names(data), value = T) #im pretest nur items 1-6 vorhanden 7,8 kamen im post dazu
)

# ein paar ethik items müssen noch rausgenommen werden, die nur im posttest erhoben wurden. hier nur check
# data_subset1 <- data %>% select(all_of(unlist(list_items_i_tpack)))
# View(data_subset1)

## Reflection
list_items_ref <- list(
  "Ref" = grep("^RE02_", names(data), value = T)
)
# data_subset3 <- data %>% select(all_of(unlist(list_items_ref)))
# sum(data_subset3 < 0, na.rm = TRUE)

## AI Literacy
# data <- data %>% mutate(AILIT = AI35_02) # rename to sumscore
list_items_ailit <- list(
  "ailit" = grep(
    "^(AI36_04|AI36_10|AI36_11|AI36_13|AI36_15|AI36_16|AI36_17|AI36_19|AI36_24|AI36_25|AI36_27|GL21_01|GL21_02|GL21_03|GL21_04|GL21_05|GL21_06|GL21_07|GL21_08|GL21_09|GL21_10|GL21_11|GL21_12|GL21_13|GL21_14|GL21_15|GL21_16|GL21_17|GL21_18|GL21_19)", # results of all ailit items
    names(data),
    value = T
  ),
  "ailit_horn" = grep(
    "^(AI36_04|AI36_10|AI36_11|AI36_13|AI36_15|AI36_16|AI36_17|AI36_19|AI36_24|AI36_25|AI36_27)",
    names(data),
    value = T
  ), # Hornberger items
  "ailit_glat" = grep(
    "^(GL21_01|GL21_02|GL21_03|GL21_04|GL21_05|GL21_06|GL21_07|GL21_08|GL21_09|GL21_10|GL21_11|GL21_12|GL21_13|GL21_14|GL21_15|GL21_16|GL21_17|GL21_18|GL21_19)",
    names(data),
    value = T
  ) # GLAT items
)

# create new columns with the means of the lists
data <- data %>%
  mutate(
    AILIT = rowSums(cbind(AI35_02, GL20_01), na.rm = TRUE), # default sumscore overall AI Lit
    AILIThorn = rowSums(
      select(., all_of(list_items_ailit$ailit_horn)),
      na.rm = TRUE
    ),
    AILITglat = rowSums(
      select(., all_of(list_items_ailit$ailit_glat)),
      na.rm = TRUE
    ),
    TK = rowMeans(select(., all_of(list_items_i_tpack$TK)), na.rm = TRUE),
    TPK = rowMeans(select(., all_of(list_items_i_tpack$TPK)), na.rm = TRUE),
    TCK = rowMeans(select(., all_of(list_items_i_tpack$TCK)), na.rm = TRUE),
    TPACKce = rowMeans(
      select(., all_of(list_items_i_tpack$TPACK_ce)),
      na.rm = TRUE
    ),
    TPACKgenai = rowMeans(
      select(., all_of(list_items_i_tpack$TPACK_genai)),
      na.rm = TRUE
    ),
    Ethics = rowMeans(
      select(., all_of(list_items_i_tpack$Ethics)),
      na.rm = TRUE
    ),
    Ref = rowMeans(select(., all_of(list_items_ref$Ref)), na.rm = TRUE),
    TPACK_total = rowMeans(
      select(., all_of(unlist(list_items_i_tpack))),
      na.rm = TRUE
    )
  )

# check missing values in TPACK and PU scales (NA means, not answered (-1 diff. answer, -9 not answered))
data %>%
  select(all_of(c(list_items_i_tpack) %>% unlist)) %>%
  summarise(across(everything(), ~ sum(is.na(.x)))) %>%
  sum # 0

```

# Methods

## Participants

```{r participants}
p_load(dplyr, tidyr) # needs to be called for rendering to work
data_participants <- data %>%
  filter(time == "pre") %>%
  group_by(intervention, location, gender) %>%
  summarise(
    n = n(),
    n_complete = sum(complete.cases(.)),
    age_min = min(age, na.rm = T),
    age_max = max(age, na.rm = T),
    age_mean = mean(age, na.rm = T) %>% round(2),
    age_sd = sd(age, na.rm = T) %>% round(2),
    semester_min = min(semester, na.rm = T),
    semester_max = max(semester, na.rm = T),
    semester_mean = mean(semester, na.rm = T) %>% round(2),
    semester_sd = sd(semester, na.rm = T) %>% round(2)
  ) %>%
  ungroup()
```

### table

```{r table-participants, result = "asis"}
#| label: tbl-participants
#| tbl-cap: "Demographic Data of the Three Experimental Groups."
# render as table
format <- ifelse(
  knitr::is_html_output(),
  "markdown",
  ifelse(knitr::is_latex_output(), "latex", "markdown")
)

var_names <- list(
  gender = "Gender",
  age = "Age",
  semester = "Semester Number",
  students = "Study Level",
  isp = "Completed Integrated Semester Internship",
  subject1 = "Subject 1",
  subject2 = "Subject 2",
  studies = "Study Program",
  location = "University",
  TK = "Intelligent TK",
  TCK = "Intelligent TCK",
  TPK = "Intelligent TPK",
  TPACK_total = "Intelligent TPACK",
  AILIT = "AI Literacy",
  Ethics = "AI Ethics",
  Ref = "Reflection"
)

kable(
  summary(
    tableby(
      intervention ~
        location +
        age +
        gender +
        semester +
        students +
        TK +
        TCK +
        TPK +
        TPACK_total +
        Ethics +
        AILIT +
        Ref,
      data %>%
        filter(time == "pre") %>%
        mutate(
          gender = factor(gender, labels = c("Female", "Male")),
          students = factor(students, labels = c("Bachelor", "Master"))
        ) %>%
        droplevels(),
      cat.test = "chisq",
      chisq.correct = T,
      control = tableby.control(test = T, total = T, digits = 2)
    ),
    labelTranslations = var_names,
    pfootnote = T,
    text = F
  ),
  escape = T,
  format = format,
  booktabs = T
)
```


## Analysis

```{r analysis-setup}
#define vars
controls <- c("gender", "semester", "location")
random_terms_lmer <- c("(1 | code)")
groups <- c("intervention")
time <- "time"
outcomes <- c(
  "AILIT",
  "AILIThorn",
  "AILITglat",
  "TK",
  "TPK",
  "TCK",
  "TPACKce",
  "TPACKgenai",
  "Ethics",
  "Ref"
)
vars_num <- c("age", "semester") # numeric outcomes
vars_cat <- c("gender", "students") # categorical outcomes`
```

## Effect Sizes

```{r effect-sizes}
# #| eval: false
# lmers_prepost_all <-
#   lapply(
#     outcomes,
#     fit_lmer,
#     groups,
#     time,
#     controls,
#     random_terms_lmer,
#     NULL,
#     data = data
#   )

# dhat <- function(model, idx = 3, type = 2) {
#   f <- abs(tail(summary(model)$coefficients, idx))[1]
#   v <- sqrt(tail(anova(model, type = type)[["Mean Sq"]], 1))
#   return(f / v)
# }
# #' Compute standardized effect size d for one fixed effect in an lmer model, based on https://pmc.ncbi.nlm.nih.gov/articles/PMC6646942/
# #'
# #' d = estimate / sqrt(sum of variances of random effects [+ residual if chosen])
# #'
# #' @param model lmer model
# #' @param effect character, name of the fixed effect in fixef(model)
# #' @param include_residual logical, include residual variance (default TRUE)
# #' @return numeric, effect size d
# lmer_d <- function(model, effect, include_residual = TRUE) {
#   stopifnot(effect %in% names(lme4::fixef(model)))

#   # numerator
#   est <- unname(lme4::fixef(model)[effect])

#   # variance components
#   vc <- as.data.frame(lme4::VarCorr(model)) # grp, var1, var2, vcov, sdcor
#   var_random <- sum(vc$vcov, na.rm = TRUE)

#   # residual
#   if (!include_residual) {
#     var_random <- var_random - sigma(model)^2
#   }

#   d <- est / sqrt(var_random)
#   return(d)
# }

# effect_sizes_dhat_old <- sapply(lmers_prepost_all, dhat, idx = 2) %>% round(2)

# effect_sizes <- sapply(
#   lmers_prepost_all,
#   lmer_d,
#   "intervention-c+STEM_language:time-pre+post"
# ) %>%
#   round(2)
# effect_sizes
```


### Ancova
```{r ancova}
# reshape data to wide format for ancova
data_wide <- data %>%
  pivot_wider(
    id_cols = c(
      code,
      intervention,
      group,
      gender,
      semester,
      students,
      location
    ),
    names_from = time,
    values_from = all_of(outcomes)
  ) %>%
  mutate(
    # scale the posttest score so that the estimates are approximations of Cohen's d
    across(all_of(outcomes %>% paste0("_post")), scale),
    treatment = factor(ifelse(
      intervention == "control",
      "control",
      "intervention"
    ))
  )

contrasts.treatment <- cbind(c(-1 / 2, 1 / 2))
colnames(contrasts.treatment) <- c("-c+t")
contrasts(data_wide$treatment) <- contrasts.treatment

ancovas <- lapply(
  outcomes,
  fit_ancova,
  groups,
  # we remove University as a covariate as we only have control students at University 2
  setdiff(controls, "location"),
  "HC3",
  data_wide
)
names(ancovas) <- outcomes

ancovas_two_groups <- lapply(
  outcomes,
  fit_ancova,
  "treatment",
  setdiff(controls, "location"),
  "HC3",
  data_wide
)
names(ancovas_two_groups) <- outcomes

```


## Intelligent TPACK and AI Ethics

::: {.landscape}
```{r tab.layout="autofit"}
#| label: tbl-ancova-tpack-summary
#| tbl-cap: "Summary of Multiple Regression Models for Intelligent TPACK Subscales and AI Ethics"

ft_ancova <- modelsummary_models(
  ancovas[grepl("^(T|Ethics)", names(ancovas))],
  outcomes = outcomes %>% grep("^(T|Ethics)", ., value = TRUE),
  output = modelsummary_output,
  # coef_rename = c("genderMännlich" = "Geschlecht")
) # %>%   kableExtra::scroll_box(width = "100%")

if (is_word) {
  ft_ancova <- adjust_table_for_word(ft_ancova, width = 1)
}
ft_ancova
```

:::

## AI Literacy

```{r tab.layout = "autofit"}
#| label: tbl-ancova-ailit-summary
#| tbl-cap: "Summary of Multiple Regression Models for AI Literacy."

ft_ailit_ancova <- modelsummary_models(
  ancovas[names(ancovas) %in% c("AILIT", "AILIThorn", "AILITglat")],
  outcomes = c("AILIT", "AILIThorn", "AILITglat"),
  output = modelsummary_output,
  # coef_rename = c("genderMännlich" = "Geschlecht")
) # %>%   kableExtra::scroll_box(width = "100%")

if (is_word) {
  ft_ailit_ancova <- adjust_table_for_word(ft_ailit_ancova, width = .75)
}
ft_ailit_ancova
```

## Critical Reflection

::: {.landscape}
```{r tab.layout="autofit"}
#| label: tbl-ancova-ref-summary
#| tbl-cap: "Summary of Multiple Regression Models for Reflection subscale."

ft_ailit_ancova <- modelsummary_models(
  ancovas[names(ancovas) %in% c("Ref")],
  outcomes = c("Ref"),
  output = modelsummary_output,
  # coef_rename = c("genderMännlich" = "Geschlecht")
) # %>%   kableExtra::scroll_box(width = "100%")

if (is_word) {
  ft_ailit_ancova <- adjust_table_for_word(ft_ailit_ancova, width = .75)
}
ft_ailit_ancova
```

:::

```{r, results="asis"}
if (!is_word) {
  cat("### Pairwise Contrasts Between Groups")
}
```

```{r ailit-ancova-between-contrasts}
# pairwise between contrasts (no multiplicity adjustment)
ailit_ancova_between_contrasts <- lapply(ancovas[1:3], function(m) {
  emmeans(m, ~intervention) %>%
    contrast(interaction = "pairwise", adjust = "none")
})
if (!is_word) {
  print(ailit_ancova_between_contrasts)
}
```

## Two Groups (Control vs. Intervention)

::: {.callout-note}
Due to the very small (insignificant) difference between the distribution of gender in the treatment groups, we could drop it from the covariates.

:::

```{r effectsizes-covariates-two-groups}
# #| eval: false
# # perform chi square for categorical variables
# chisquare_covariates_two_groups <- vars_cat %>%
#   lapply(function(v) {
#     tab <- table(d[[v]], d$treatment)
#     chisq <- chisq.test(tab)
#   })
# names(chisquare_covariates_two_groups) <- vars_cat

# chisquare_covariates_two_groups

# effectsizes_covariates__two_groups %>% kable
```

```{r ancova-two-groups}
#| label: tbl-ancova-two-groups
#| tbl-cap: "Summary of Multiple Linear Regression Models for Two Treatment Groups."

modelsummary_models(
  ancovas_two_groups,
  outcomes = outcomes,
  output = modelsummary_output
)

```


```{r save-env }
# save environment
save.image("data/env-analysis.Rdata")
```